### ISSUE TITLE
No feedback if proper font is used

### ISSUE THREAD

**Issue by varac** [philj56/tofi#70] opened 2022-11-28 11:10 UTC
There's no log message that the specified font is not found:

```
rm ~/.config/tofi/config
$ tofi-drun --font FOOBAR

$ tofi-drun --font /fhhf/fwrfer.ttf
```

**Comment by philj56** [comment] 2022-11-28 11:42
Yeah, this is a slightly annoying thing that I don't think there's any good way to fix. Tofi handles fonts like this:

- Check if the argument to `--font` is a file that it can open
  - If it is, use that with the Harfbuzz backend
  - If not, use the Pango backend, and pass the option to Pango

The problem is that I can't warn that the file wasn't found, because you may have passed a font name to `--font`. Then, I can't warn if the named font wasn't found, as Pango provides no feedback on this as far as I know - it just silently falls back to an existing font via FontConfig.

**Comment by philj56** [comment] 2022-12-01 22:10
I've looked into this a bit more, and as far as I can see there's no way to do this properly. Pango just doesn't allow you to determine if the font that got loaded was the one you wanted, and I don't think it's Pango's fault.

The closest thing I can find would be to list all available font families, and check if the requested one is there. Not only does this slow down the Pango backend even more, but it doesn't even work if you validly run e.g.
```sh
tofi --font monospace
```
You'd expect this to select your default monospace font, and it does. However, "monospace" isn't the name of a font on the system, so it won't show up in the list.

From some brief looking into the FontConfig (which Pango uses) docs, font lookup is done via [`FcFontSetMatch`](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcfontsetmatch.html). This will "return the best font from a set of font sets". There's no mention of what happens if no fallback is found - I assume because everything falls back to the system default font.

So unfortunately, I think this simply isn't possible, or at least not in any sort of reliable way. I'll therefore close this as not planned. Thanks for the suggestion though!

**Closed by philj56** 2022-12-01 22:10 UTC
